# Generated by Django 2.2.4 on 2019-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notemaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('definitions', models.TextField(blank=True, null=True)),
                ('examples', models.TextField(blank=True, null=True)),
                ('expressions', models.TextField(blank=True, null=True)),
                ('image_urls', models.TextField(blank=True, null=True)),
                ('grammar', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
