# Generated by Django 2.2.4 on 2019-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notemaker', '0003_searchresult_ipa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='definitions',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='expressions',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='grammar',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='ipa',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
