# Generated by Django 2.2.3 on 2019-07-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytime', '0004_auto_20190729_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
