# Generated by Django 2.2.4 on 2019-11-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notemaker', '0005_auto_20191108_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
