# Generated by Django 2.2.4 on 2019-11-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notemaker', '0007_card_cardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='expression',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='expression_meaning',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notemaker.CardType'),
        ),
        migrations.AlterField(
            model_name='card',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notemaker.Note'),
        ),
    ]
