# Generated by Django 2.2.3 on 2019-07-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_author', models.CharField(max_length=200)),
                ('original_source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('main_text', models.TextField()),
                ('translation_author', models.CharField(max_length=200)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storytime.Story')),
            ],
        ),
    ]
