# Generated by Django 2.2.3 on 2019-07-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytime', '0003_auto_20190729_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='translation_author',
            new_name='author',
        ),
    ]
