# Generated by Django 2.2.4 on 2019-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notemaker', '0004_auto_20191108_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
