# Generated by Django 2.2.4 on 2019-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notemaker', '0006_auto_20191108_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('success', models.IntegerField(default=0)),
                ('failure', models.IntegerField(default=0)),
                ('fails_in_a_row', models.IntegerField(default=0)),
                ('success_in_a_row', models.IntegerField(default=0)),
                ('card_type', models.ForeignKey(on_delete='models.CASCADE', to='notemaker.CardType')),
                ('note', models.ForeignKey(on_delete='models.CASCADE', to='notemaker.Note')),
            ],
        ),
    ]
