# Generated by Django 2.2.4 on 2020-01-19 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notemaker', '0008_auto_20191110_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
